repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.29.2
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/AleksaC/terraform-py
    rev: v1.9.5
    hooks:
      - id: tf-fmt

  - repo: https://github.com/AleksaC/tflint-py
    rev: v0.53.0
    hooks:
      - id: tflint
